/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/wheelc.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.009']}
        position={[0.508, 2.555, -0.436]}
        rotation={[0.017, -0.107, -0.138]}
        scale={[1.21, 1.534, 6.639]}
      />
      <group
        position={[-0.453, 11.586, -0.056]}
        rotation={[0.006, -0.157, -1.535]}
        scale={[2.309, 0.776, 2.309]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024_1.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus011.geometry}
        material={materials['Material.004']}
        position={[0.028, 11.391, 0.03]}
        rotation={[0.009, -0.174, -1.518]}
        scale={2.621}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
        position={[1.955, 10.054, -6.498]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials['Material.001']}
        position={[1.906, 7.047, -4.97]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={materials['Material.001']}
        position={[1.496, 5.209, -2.021]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials['Material.001']}
        position={[0.658, 5.154, 2.231]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={materials['Material.001']}
        position={[-0.027, 7.112, 5.371]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={materials['Material.001']}
        position={[1.734, 13.271, -6.414]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere010.geometry}
        material={materials['Material.001']}
        position={[1.293, 16.282, -5.125]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.001']}
        position={[0.782, 18.082, -2.822]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials['Material.001']}
        position={[0.161, 18.611, 0.689]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={materials['Material.001']}
        position={[-0.367, 10.855, 6.894]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere012.geometry}
        material={materials['Material.001']}
        position={[-0.708, 13.664, 6.581]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere013.geometry}
        material={materials['Material.001']}
        position={[-0.43, 17.164, 4.19]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.383}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere009.geometry}
        material={materials['Material.001']}
        position={[0.149, 11.654, -0.008]}
        scale={-0.468}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials['Material.001']}
        position={[-0.483, 11.874, 5.814]}
        rotation={[1.993, -0.898, -2.645]}
        scale={[0.427, 0.807, 0.471]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[0.314, 10.503, -1.977]}
        rotation={[0.843, 0.067, -1.344]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials['Material.011']}
        position={[0.153, 8.974, -0.442]}
        rotation={[-0.023, -0.001, -1.524]}
        scale={2.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={nodes.Text003.material}
        position={[-0.078, 10.671, 0.943]}
        rotation={[-0.642, -0.14, -1.649]}
        scale={[0.906, 0.616, 1.646]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={nodes.Text004.material}
        position={[-0.019, 12.91, -0.814]}
        rotation={[2.69, 0.226, -1.486]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials['Material.011']}
        position={[0.684, 13.443, -4.867]}
        rotation={[-0.023, -0.001, -1.524]}
        scale={2.173}
      />
    </group>
  )
}

useGLTF.preload('/wheelc.glb')


