/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const MonsterModal=(anime)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/manster.glb')
  const { actions } = useAnimations(animations, group)
  const anim="Typing"
  useEffect(()=>{
   
    anime && actions[anime.anime].reset().play()
    console.log(' anime: ',  anime);
  },[anime])
  return (
    <>
   
    <group ref={group}  dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="MutantMesh"
            geometry={nodes.MutantMesh.geometry}
            material={materials.mutant_M}
            skeleton={nodes.MutantMesh.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/manster.glb')
export default MonsterModal